apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    joindevops_path: "https://learn.joindevops.com/learn/home/DAWS-81S/section/550162/lesson/3431240?"
spec:
  containers:
  - name: nginx
    image: nginx