apiVersion: v1
kind: Pod
metadata:
  name: resource-limits
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 75Mi
      limits:
        cpu: 200m
        memory: 100Mi
